name: Documentation
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Validate openAPI
      id: validate
      uses: mbowman100/swagger-validator-action@2.0
      with:
        files: tdlight-api-openapi.yaml
